#version: "3.8"
networks:
  shared-network:
    external: true

services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres-zoomcamp
    ports:
      - "5431:5431"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - shared-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "3000:80"
volumes:
  postgres-data: